### ISSUE TITLE
Sorry! I did not find the gradient color customization of the button component

### ISSUE THREAD

**Issue by lly0414** [WrathChaos/react-native-button#13]
I didn't find a way to customize the gradient color. Then I checked the source code and found that the gradient color cannot be customized. Am I correct?
> [code](https://github.com/WrathChaos/react-native-button/blob/6d588ac3c76620bf0ba5ec22723555ba22c2e672/lib/ClassicButton/Button.tsx#L53)

**Comment by WrathChaos** [comment]
Hello @lly0414,

There is `prop-drilling` for `LinearGradient` you should be able to use `colors` prop to change the gradient colours. Can you try it?

**Comment by lly0414** [comment]
```js
<Button
  style={searchStyle.searchButton}
  gradient
  height={42}
  width={100}
  textColor="white"
  colors={['#4c669f', '#3b5998', '#192f6a']}
  iconDisable
  text="Search"
/>
```
Is it so? But it didn't work

**Comment by WrathChaos** [comment]
Helloo @lly0414 ,

You're right it was not customizable. I released a new version, you should be able to customize whole gradient component

## [Release 1.0.3 😇](https://github.com/WrathChaos/react-native-button/releases/tag/1.0.3)

**Comment by lly0414** [comment]
```
While trying to resolve module `@freakycoder/react-native-button` from file `F:\AwesomeProject\src\scenes\find\components\topSearch.js`, the package `F:\AwesomeProject\node_modules\@freakycoder\react-native-button\package.json` was successfully found. However, this package itself specifies a `main` module field that could not be resolved (`F:\AwesomeProject\node_modules\@freakycoder\react-native-button\build\dist\index.js`. Indeed, none of these files exist:
```
hello @WrathChaos 
There seems to be something wrong with the npm package you published

**Comment by WrathChaos** [comment]
Hey @lly0414,
Really sorry about that, totally my fault.

Here is the new working release: 

## [Release 1.0.4](https://github.com/WrathChaos/react-native-button/releases/tag/1.0.4)

**Comment by lly0414** [comment]
That's nothing
I still think it's great, so I have been waiting for it to be available

**Comment by lly0414** [comment]
Ready to use
Thank you👍

**Comment by WrathChaos** [comment]
Please feel free to open new issues and feature requests :)
