### ISSUE TITLE
I want to modify the background color, but it doesn't take effect

### ISSUE THREAD

**Issue by lly0414** [WrathChaos/react-native-button#8]
### Code
```js
<Button
  style={styles.searchButton}
  gradient
  height={42}
  width={100}
  textColor="white"
  shadowColor="#035ffe"
  backgroundColor="#035ffe"
  borderColor="#035ffe"
  iconDisable
/>
```

**Comment by WrathChaos** [comment]
Hello @lly0414 
Thank you for using this library :) 

You're set the `gradient` prop so you cannot set the backgroundColor with this prop. Try the `solid` prop instead of `gradient` one.

**Comment by lly0414** [comment]
I think it's great😄
I want to use the gradient, can't you set the gradient color by yourself?

**Comment by WrathChaos** [comment]
It is possible with the new 1.0.0 version :) 

There are some breaking changes but it is re-written with Typescript. It is not published yet, there is a bug right now. It will be available today :) 

 I will inform you.

**Comment by lly0414** [comment]
Ok

**Comment by WrathChaos** [comment]
Hello @lly0414 ,

Here is the new version

## [Release 1.0.2 🥳](https://github.com/WrathChaos/react-native-button/releases/tag/1.0.2)

You can customize almost anything :) Please feel free to open a new issue if you have a problem

**Comment by lly0414** [comment]
thanks 🎉🎉🎉
